// 拠点一覧
export const resources = [
  { id: "RC-hY7CuvT2dLPayj8g", title: "盛岡本社" },
  { id: "RC-WCa6s=7jiqnmH?QO", title: "川崎支社" },
  { id: "RC-0omXWfyNlV1(a.%G", title: "高松支社" },
  { id: "RC-tsO1SA4b7Hw!UH_s", title: "美唄支社" },
  { id: "RC-?K5_3p8JIOVRR4oF", title: "仙台支社" },
];

// オペレーター一覧
export const operator = [
  { id: "DE-RQxKOBdkE7whg8DO", name: "オペレーターAさん" },
  { id: "DE-*26(0B}x[I3eV6P-", name: "オペレーターBさん" },
  { id: "DE-lhKCB=}<(E,Wr0Ai", name: "オペレーターCさん" },
  { id: "DE-KTSVs(ty=xAH#YLi", name: "オペレーターDさん" },
];

// DBから返ってくる予定の内容
export const event = [
  {
    id: 1,
    //
    operator_name: "オペレーターA",
    operator_cognito_user_id: "DE-RQxKOBdkE7whg8DO",
    //
    location_name: "盛岡支店",
    location_cognito_user_id: "RC-hY7CuvT2dLPayj8g",
    //
    title: "sample title",
    location_memo: "拠点のメモ",
    operator_memo: "オペレーターのメモ",
    avatar: "アバターD",
    start: "2023-03-21 14:00:00",
    end: "2023-03-21 18:00:00",
    //
    created_at: "2023-02-07 03:32:16",
  },
  {
    id: 2,
    //
    operator_name: "オペレーターB",
    operator_cognito_user_id: "DE-*26(0B}x[I3eV6P-",
    //
    location_name: "川崎支店",
    location_cognito_user_id: "RC-WCa6s=7jiqnmH?QO",
    //
    title: "sample title",
    location_memo: "拠点のメモ",
    operator_memo: "オペレーターのメモ",
    avatar: "アバターC",
    start: "2023-03-07 10:00:00",
    end: "2023-03-07 16:00:00",
    //
    created_at: "2023-02-07 03:32:16",
  },
];

// イベント一覧
// DBから撮ってきたのを整形したものってことにする
export const events = [
  {
    id: "2",
    title: "sample title",
    resourceId: "2",
    start: new Date("2023/3/21 20:00").getTime(),
    end: new Date("2023/3/21 22:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターBさん",
      locationName: "",
      avatar: "アバターE",
    },
    color: "",
    durationEditable: false,
  },
  {
    id: "3",
    title: "sample title",
    resourceId: "3",
    start: new Date("2023/2/21 11:00").getTime(),
    end: new Date("2023/2/21 20:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターCさん",
      locationName: "",
      avatar: "アバターE",
    },
    // groupId: '',
    color: "",
    durationEditable: false,
  },
  {
    id: "4",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/2/21 15:00").getTime(),
    end: new Date("2023/2/21 20:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターDさん",
      locationName: "",
      avatar: "アバターE",
    },
    color: "",
    durationEditable: false,
    // constraint: 'sample1',
  },
  {
    id: "5",
    title: "sample title",
    resourceId: "4",
    start: new Date("2023/2/21 11:00").getTime(),
    end: new Date("2023/2/21 19:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターEさん",
      locationName: "",
      avatar: "アバターE",
    },
    durationEditable: false,
  },
  {
    id: "6",
    title: "sample title",
    resourceId: "4",
    start: new Date("2023/2/19 11:00").getTime(),
    end: new Date("2023/2/19 15:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターLさん",
      locationName: "",
      avatar: "アバターE",
    },
    durationEditable: false,
  },
  {
    id: "7",
    title: "sample title",
    resourceId: "3",
    start: new Date("2023/2/16 10:00").getTime(),
    end: new Date("2023/2/16 19:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターLさん",
      locationName: "",
      avatar: "アバターE",
    },
    color: "",
    durationEditable: false,
  },
  {
    id: "8",
    title: "",
    resourceId: "1",
    start: new Date("2023/2/14 10:00").getTime(),
    end: new Date("2023/2/14 19:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターMさん",
      locationName: "",
      avatar: "アバターE",
    },
    color: "",
    durationEditable: false,
  },
  {
    id: "9",
    title: "",
    resourceId: "2",
    start: new Date("2023/2/27 16:00").getTime(),
    end: new Date("2023/2/27 22:30").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターMさん",
      locationName: "",
      avatar: "アバターE",
    },
    color: "",
    durationEditable: false,
  },
  {
    id: "10",
    title: "sample title",
    resourceId: "2",
    start: new Date("2023/2/3 16:00").getTime(),
    end: new Date("2023/2/3 22:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターMさん",
      locationName: "",
      avatar: "アバターE",
    },
    durationEditable: false,
  },
  {
    id: "10",
    title: "sample title",
    resourceId: "2",
    start: new Date("2023/3/3 9:00").getTime(),
    end: new Date("2023/3/3 18:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターMさん",
      locationName: "",
      avatar: "アバターE",
    },
    durationEditable: false,
  },
  {
    id: "11",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/2/11 15:00").getTime(),
    end: new Date("2023/2/11 20:00").getTime(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "盛岡支店",
      avatar: "アバターE",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "12",
    title: "sample title",
    resourceId: "2",
    start: new Date("2023/4/21 15:00").getTime(),
    end: new Date("2023/4/21 20:00").getTime(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターAさん",
      locationName: "川崎支店",
      avatar: "アバターE",
    },
    color: "#ff9f89",
    display: "",
    durationEditable: false,
  },
  {
    id: "13",
    title: "sample title",
    resourceId: "3",
    start: new Date("2023/4/16 15:00").getTime(),
    end: new Date("2023/4/16 20:00").getTime(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "高松支店",
      avatar: "アバターE",
    },
    color: "",
    display: "",
    durationEditable: false,
  },

  {
    id: "14",
    title: "sample title",
    resourceId: "2",
    start: new Date("2023/3/25 10:00").getTime(),
    end: new Date("2023/3/25 20:00").getTime(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "川崎支店",
      avatar: "アバターL",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "15",
    title: "sample title",
    resourceId: "3",
    start: new Date("2023/3/01 10:00").getTime(),
    end: new Date("2023/3/01 20:00").getTime(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "高松支店",
      avatar: "アバターX",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
];

export const eventConstraints = [
  {
    id: "sample1",
    groupId: "sample1",
    resourceId: "1",
    display: "background",
  },
  {
    id: "sample2",
    groupId: "sample2",
    resourceId: "3",
    display: "background",
  },
];

export const externalEvents = [
  {
    title: "",
    extendedProps: {
      memo: "",
      operatorName: "オペレーターKさん",
      Username: "RC-HvIzf9STs8JB3M5Q",
      avatar: "",
    },
    color: "",
    id: "",
  },
  {
    title: "",
    extendedProps: {
      memo: "",
      operatorName: "オペレーターLさん",
      Username: "RC-t6vWhbAiYLSUT2kR",
      avatar: "",
    },
    color: "",
    id: "",
  },
  {
    title: "",
    extendedProps: {
      memo: "",
      operatorName: "オペレーターMさん",
      Username: "RC-ijuixbWWY8lww4US",
      avatar: "",
    },
    color: "",
    id: "",
  },
  {
    title: "",
    extendedProps: {
      memo: "",
      operatorName: "オペレーターNさん",
      Username: "RC-WvD67gCo7h24mCud",
      avatar: "",
    },
    color: "",
    id: "",
  },
];

// DBから撮ってきたのを整形したものってことにする
export const operatorEvents = [
  {
    id: "1",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/2/11 15:00").toISOString(),
    end: new Date("2023/2/11 20:00").toISOString(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "盛岡支店",
      avatar: "アバターE",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "2",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/4/21 15:00").toISOString(),
    end: new Date("2023/4/21 20:00").toISOString(),
    extendedProps: {
      memo: "",
      operatorName: "オペレーターAさん",
      locationName: "川崎支店",
      avatar: "アバターE",
    },
    color: "#ff9f89",
    display: "",
    durationEditable: false,
  },
  {
    id: "3",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/4/16 15:00").toISOString(),
    end: new Date("2023/4/16 20:00").toISOString(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "高松支店",
      avatar: "アバターE",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "4",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/3/21 15:00").toISOString(),
    end: new Date("2023/3/21 20:00").toISOString(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "川崎支店",
      avatar: "アバターK",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "5",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/3/25 10:00").toISOString(),
    end: new Date("2023/3/25 20:00").toISOString(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "川崎支店",
      avatar: "アバターL",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
  {
    id: "6",
    title: "sample title",
    resourceId: "1",
    start: new Date("2023/3/01 10:00").toISOString(),
    end: new Date("2023/3/01 20:00").toISOString(),
    extendedProps: {
      memo: "遅れるかも",
      operatorName: "オペレーターAさん",
      locationName: "高松支店",
      avatar: "アバターX",
    },
    color: "",
    display: "",
    durationEditable: false,
  },
];
